#ifndef RADIXTREE_STATUS_H
#define RADIXTREE_STATUS_H

typedef enum {
  RADIXTREE_OK = 0,
  RADIXTREE_EXISTS,
  RADIXTREE_NOTFOUND,
  RADIXTREE_REPLACED,
  RADIXTREE_ERR_NOMEM,
  RADIXTREE_ERR_INVAL,
  RADIXTREE_ERR_OVERFLOW,
  RADIXTREE_ERR_UNDERFLOW,
} radixtree_status;

#endif  // RADIXTREE_STATUS_H